# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'AnimationBST' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#  pod 'BaseBinTree', :git => 'https://github.com/BoyHsu/BaseBinTree.git', :tag => '1.0.1'
  pod 'BaseBinTree', :path => 'AnimationBST/BaseBinTree'
 
end
